// Research-set inventory transcribed from the supplied source document (2026-07-11).
// The status fields are a conservative first-pass triage; each row links to its evidence starting point.
const appRows = [
  ["CRM & Sales","Salesforce","salesforce.com"],["CRM & Sales","HubSpot","hubspot.com"],["CRM & Sales","Pipedrive","pipedrive.com"],["CRM & Sales","Attio","attio.com"],["CRM & Sales","Twenty","twenty.com"],["CRM & Sales","Podio","podio.com"],["CRM & Sales","Zoho CRM","zoho.com/crm"],["CRM & Sales","Close","close.com"],["CRM & Sales","Copper","copper.com"],["CRM & Sales","DealCloud","api.docs.dealcloud.com"],
  ["Support & Helpdesk","Zendesk","zendesk.com"],["Support & Helpdesk","Intercom","intercom.com"],["Support & Helpdesk","Freshdesk","freshdesk.com"],["Support & Helpdesk","Front","front.com"],["Support & Helpdesk","Pylon","usepylon.com"],["Support & Helpdesk","LiveAgent","liveagent.com"],["Support & Helpdesk","Plain","plain.com"],["Support & Helpdesk","Help Scout","helpscout.com"],["Support & Helpdesk","Gorgias","gorgias.com"],["Support & Helpdesk","Gladly","gladly.com"],
  ["Communications","Slack","slack.com"],["Communications","Twilio","twilio.com"],["Communications","Zoho Cliq","zoho.com/cliq"],["Communications","Lark","open.larksuite.com"],["Communications","Pumble","pumble.com"],["Communications","Discord","discord.com"],["Communications","Telegram","core.telegram.org"],["Communications","WhatsApp Business","developers.facebook.com/docs/whatsapp"],["Communications","Aircall","aircall.io"],["Communications","Vonage","developer.vonage.com"],
  ["Marketing, Ads & Social","Google Ads","developers.google.com/google-ads"],["Marketing, Ads & Social","Meta Ads","developers.facebook.com/docs/marketing-apis"],["Marketing, Ads & Social","LinkedIn Ads","learn.microsoft.com/linkedin/marketing"],["Marketing, Ads & Social","GoHighLevel","highlevel.stoplight.io"],["Marketing, Ads & Social","Mailchimp","mailchimp.com/developer"],["Marketing, Ads & Social","Klaviyo","developers.klaviyo.com"],["Marketing, Ads & Social","systeme.io","systeme.io"],["Marketing, Ads & Social","Pinterest","developers.pinterest.com"],["Marketing, Ads & Social","Threads","developers.facebook.com/docs/threads"],["Marketing, Ads & Social","SendGrid","sendgrid.com"],
  ["Ecommerce","Shopify","shopify.dev"],["Ecommerce","WooCommerce","woocommerce.com/document/woocommerce-rest-api"],["Ecommerce","BigCommerce","developer.bigcommerce.com"],["Ecommerce","Salesforce Commerce Cloud","developer.salesforce.com/docs/commerce"],["Ecommerce","Magento / Adobe Commerce","developer.adobe.com/commerce"],["Ecommerce","Squarespace","developers.squarespace.com"],["Ecommerce","Ecwid","api-docs.ecwid.com"],["Ecommerce","Gumroad","gumroad.com/api"],["Ecommerce","Amazon Selling Partner","developer-docs.amazon.com/sp-api"],["Ecommerce","fanbasis","fanbasis.com"],
  ["Data, SEO & Scraping","DataForSEO","docs.dataforseo.com"],["Data, SEO & Scraping","SE Ranking","seranking.com/api"],["Data, SEO & Scraping","Ahrefs","ahrefs.com/api"],["Data, SEO & Scraping","MrScraper","docs.mrscraper.com"],["Data, SEO & Scraping","Apify","docs.apify.com"],["Data, SEO & Scraping","Firecrawl","firecrawl.dev"],["Data, SEO & Scraping","Bright Data","brightdata.com"],["Data, SEO & Scraping","Sherlock","github.com/sherlock-project/sherlock"],["Data, SEO & Scraping","Waterfall.io","waterfall.io"],["Data, SEO & Scraping","Clay","clay.com"],
  ["Developer, Infra & Data","GitHub","docs.github.com/rest"],["Developer, Infra & Data","Vercel","vercel.com/docs/rest-api"],["Developer, Infra & Data","Netlify","docs.netlify.com/api"],["Developer, Infra & Data","Cloudflare","developers.cloudflare.com/api"],["Developer, Infra & Data","Supabase","supabase.com/docs"],["Developer, Infra & Data","Neo4j","neo4j.com/docs/api"],["Developer, Infra & Data","Snowflake","docs.snowflake.com"],["Developer, Infra & Data","MongoDB Atlas","mongodb.com/docs/atlas/api"],["Developer, Infra & Data","Datadog","docs.datadoghq.com/api"],["Developer, Infra & Data","Sentry","docs.sentry.io/api"],
  ["Productivity & PM","Notion","developers.notion.com"],["Productivity & PM","Airtable","airtable.com/developers"],["Productivity & PM","Linear","developers.linear.app"],["Productivity & PM","Jira","developer.atlassian.com"],["Productivity & PM","Asana","developers.asana.com"],["Productivity & PM","Monday.com","developer.monday.com"],["Productivity & PM","ClickUp","clickup.com/api"],["Productivity & PM","Coda","coda.io/developers"],["Productivity & PM","Smartsheet","smartsheet.com/developers"],["Productivity & PM","Harvest","help.getharvest.com/api-v2"],
  ["Finance & Fintech","Stripe","stripe.com/docs/api"],["Finance & Fintech","Plaid","plaid.com/docs"],["Finance & Fintech","Binance","binance-docs.github.io"],["Finance & Fintech","Paygent Connect","paygent.co.jp"],["Finance & Fintech","iPayX","ipayx.ai/docs"],["Finance & Fintech","QuickBooks","developer.intuit.com"],["Finance & Fintech","Xero","developer.xero.com"],["Finance & Fintech","Brex","developer.brex.com"],["Finance & Fintech","Ramp","docs.ramp.com"],["Finance & Fintech","PitchBook","pitchbook.com"],
  ["AI, Research & Media","NotebookLM","cloud.google.com/gemini"],["AI, Research & Media","Otter AI","help.otter.ai"],["AI, Research & Media","Fathom","fathom.video"],["AI, Research & Media","Consensus","consensus.app"],["AI, Research & Media","Reducto","reducto.ai"],["AI, Research & Media","Devin","docs.devin.ai"],["AI, Research & Media","higgsfield","higgsfield.ai/cli"],["AI, Research & Media","Mermaid CLI","github.com/mermaid-js/mermaid-cli"],["AI, Research & Media","YouTube Transcript","transcriptapi.com"],["AI, Research & Media","Grain","grain.com"]
];

const admin = new Set(["Salesforce","Zoho CRM","DealCloud","Front","Pylon","LiveAgent","Gladly","Zoho Cliq","Lark","WhatsApp Business","Aircall","Google Ads","Meta Ads","LinkedIn Ads","Threads","Salesforce Commerce Cloud","Magento / Adobe Commerce","Amazon Selling Partner","Bright Data","Waterfall.io","Clay","Snowflake","MongoDB Atlas","Smartsheet","QuickBooks","PitchBook","NotebookLM","Otter AI","Grain"]);
const gated = new Set(["DealCloud","Gladly","GoHighLevel","systeme.io","Salesforce Commerce Cloud","Amazon Selling Partner","Waterfall.io","PitchBook","NotebookLM","Consensus","Devin","higgsfield","YouTube Transcript"]);
const keys = new Set(["Twilio","Telegram","SendGrid","DataForSEO","SE Ranking","Ahrefs","Apify","Firecrawl","Bright Data","Cloudflare","Supabase","Datadog","Stripe","Plaid","Binance","Paygent Connect","iPayX","Brex","Ramp","Reducto","Mermaid CLI","YouTube Transcript"]);
const noPublic = new Set(["Twenty","Pylon","Plain","Pumble","systeme.io","fanbasis","Waterfall.io","NotebookLM","Consensus","higgsfield","Grain"]);
const oauth = new Set(["Slack","Discord","Lark","WhatsApp Business","Google Ads","Meta Ads","LinkedIn Ads","Pinterest","Threads","Shopify","BigCommerce","Squarespace","Ecwid","GitHub","Vercel","Netlify","Notion","Airtable","Linear","Jira","Asana","Monday.com","ClickUp","Coda","QuickBooks","Xero","Otter AI","Devin"]);
const existingMcp = new Set(["Otter AI","Devin"]);

const apps = appRows.map(([category, name, hint], index) => {
  const isGated = gated.has(name), isAdmin = admin.has(name), isNoPublic = noPublic.has(name);
  const auth = oauth.has(name) ? "OAuth 2.0" : keys.has(name) ? "API key / token" : "Token or API key";
  const access = isGated ? "Gated" : isAdmin ? "Admin" : "Self-serve";
  const surface = isNoPublic ? "No public API confirmed" : "Documented REST • focused";
  const verdict = isGated ? "Outreach" : isNoPublic ? "Validate" : isAdmin ? "Validate" : "Build now";
  return {id:index + 1, name, category, description:`${category} workflow integration.`, auth, access, surface, verdict, mcp:existingMcp.has(name), source:`https://${hint}`};
});
